image:
  file: .gitpod.dockerfile

ports:
  - name: Django Server
    port: 8000
    onOpen: open-preview
    
tasks:
  - name: Setup Django Environment
    init: |
      echo "DJANGO_SETTINGS_MODULE=gestaoestoque.settings" > .env
      pip install -r requirements.txt
      cd backend
      python manage.py makemigrations
      python manage.py migrate
      python manage.py collectstatic --noinput
      echo "CSRF_TRUSTED_ORIGINS = ['https://*.gitpod.io']" >> gestaoestoque/settings.py
    command: |
      cd backend
      python manage.py runserver 0.0.0.0:8000
      
vscode:
  extensions:
    - ms-python.python
    - ms-python.pylint
    - ms-python.flake8
    - bradlc.vscode-tailwindcss
