# Generated by Django 5.1.14 on 2025-11-18 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('estoque', 'Relatório de Estoque'), ('movimentacoes', 'Relatório de Movimentações'), ('vencimentos', 'Relatório de Vencimentos'), ('baixo_estoque', 'Relatório de Baixo Estoque'), ('auditoria', 'Relatório de Auditoria')], max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Relatório',
                'verbose_name_plural': 'Tipos de Relatórios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Agendamento')),
                ('frequency', models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal')], max_length=20, verbose_name='Frequência')),
                ('filters', models.JSONField(default=dict, verbose_name='Filtros')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10, verbose_name='Formato')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='Próxima Execução')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.reporttype', verbose_name='Tipo de Relatório')),
            ],
            options={
                'verbose_name': 'Agendamento de Relatório',
                'verbose_name_plural': 'Agendamentos de Relatórios',
                'ordering': ['next_run'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Template')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('filters', models.JSONField(default=dict, verbose_name='Filtros Salvos')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10, verbose_name='Formato Padrão')),
                ('is_public', models.BooleanField(default=False, help_text='Disponível para outros usuários', verbose_name='Público')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.reporttype', verbose_name='Tipo de Relatório')),
            ],
            options={
                'verbose_name': 'Template de Relatório',
                'verbose_name_plural': 'Templates de Relatórios',
                'ordering': ['name'],
                'unique_together': {('user', 'name', 'report_type')},
            },
        ),
        migrations.CreateModel(
            name='ReportGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Filtros em formato JSON', verbose_name='Filtros Aplicados')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('error', 'Erro')], default='pending', max_length=20, verbose_name='Status')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10, verbose_name='Formato')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Caminho do Arquivo')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamanho do Arquivo (bytes)')),
                ('processing_time', models.DurationField(blank=True, null=True, verbose_name='Tempo de Processamento')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('total_records', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total de Registros')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='relatorios.reporttype', verbose_name='Tipo de Relatório')),
            ],
            options={
                'verbose_name': 'Geração de Relatório',
                'verbose_name_plural': 'Gerações de Relatórios',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='relatorios__user_id_c4f586_idx'), models.Index(fields=['report_type', '-created_at'], name='relatorios__report__aef1a4_idx'), models.Index(fields=['status', '-created_at'], name='relatorios__status_3e184f_idx')],
            },
        ),
    ]
