# Generated by Django 5.1.14 on 2025-11-18 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, help_text='Chave de API para integrações externas', max_length=255, verbose_name='API Key')),
                ('api_url', models.URLField(blank=True, help_text='URL base da API externa', verbose_name='URL da API')),
                ('api_timeout', models.IntegerField(default=30, help_text='Tempo máximo de espera para requisições API', verbose_name='Timeout (segundos)')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Configurações de API',
            },
        ),
    ]
