# Generated by Django 5.1.14 on 2025-11-18 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apisettings',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='apisettings',
            name='api_timeout',
        ),
        migrations.AddField(
            model_name='apisettings',
            name='api_habilitada',
            field=models.BooleanField(default=False, help_text='Marque para ativar a integração com APIs externas.', verbose_name='Habilitar Integração via API'),
        ),
        migrations.AddField(
            model_name='apisettings',
            name='api_token',
            field=models.CharField(blank=True, help_text='Token para autenticação na API externa', max_length=255, verbose_name='Token da API'),
        ),
        migrations.AlterField(
            model_name='apisettings',
            name='api_url',
            field=models.URLField(blank=True, help_text='URL base da API externa', verbose_name='URL da API Externa'),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_suffix', models.CharField(default='Sistema ARES - Gestão de Estoque', help_text="Título do site utilizado como sufixo. Ex.: ' | Sistema ARES'", max_length=255, verbose_name='Título do Site')),
                ('menu_max_levels', models.PositiveIntegerField(default=2, help_text='Define até quantos níveis de páginas o menu principal irá exibir. (Máximo: 3)', verbose_name='Níveis máximos do menu')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Configurações do Site',
            },
        ),
    ]
