# Generated by Django 5.2.8 on 2025-11-25 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_apisettings_api_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('perfil', models.CharField(choices=[('REPR_LEGAL', 'Representante Legal'), ('REPR_DELEGADO', 'Representante Delegado'), ('OPERADOR', 'Operador')], default='OPERADOR', max_length=20, verbose_name='Perfil de Acesso')),
                ('permissoes_customizadas', models.JSONField(blank=True, default=dict, help_text='Permissões específicas além das do perfil padrão', verbose_name='Permissões Customizadas')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para desativar o acesso do usuário', verbose_name='Ativo')),
                ('data_expiracao', models.DateField(blank=True, help_text='Data em que o acesso expira (deixe em branco para nunca expirar)', null=True, verbose_name='Data de Expiração')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o perfil do usuário', verbose_name='Observações')),
                ('autorizado_por', models.ForeignKey(blank=True, help_text='Representante Legal que autorizou este acesso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_autorizados', to=settings.AUTH_USER_MODEL, verbose_name='Autorizado por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='core_perfil_user_id_c50e68_idx'), models.Index(fields=['perfil', 'ativo'], name='core_perfil_perfil_f49e38_idx')],
            },
        ),
    ]
