# Generated by Django 5.2.8 on 2025-11-25 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_perfilusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data/Hora')),
                ('action', models.CharField(choices=[('CREATE', 'Criar'), ('UPDATE', 'Atualizar'), ('DELETE', 'Excluir'), ('VIEW', 'Visualizar'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PERM_CHANGE', 'Mudança de Permissão'), ('EXPORT', 'Exportar'), ('IMPORT', 'Importar'), ('APPROVE', 'Aprovar'), ('REJECT', 'Rejeitar'), ('OTHER', 'Outro')], db_index=True, max_length=20, verbose_name='Ação')),
                ('severity', models.CharField(choices=[('LOW', 'Baixo'), ('MEDIUM', 'Médio'), ('HIGH', 'Alto'), ('CRITICAL', 'Crítico')], db_index=True, default='LOW', max_length=10, verbose_name='Severidade')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID do Objeto')),
                ('object_repr', models.CharField(blank=True, max_length=500, verbose_name='Representação do Objeto')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Dados adicionais sobre a ação (JSON)', verbose_name='Metadados')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Valores antes e depois da alteração', verbose_name='Mudanças')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Tipo de Objeto')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'user'], name='core_auditl_timesta_328bf1_idx'), models.Index(fields=['action', 'severity'], name='core_auditl_action_54e21b_idx'), models.Index(fields=['content_type', 'object_id'], name='core_auditl_content_fec0c4_idx')],
            },
        ),
    ]
