# Generated by Django 5.2.8 on 2025-11-25 23:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0004_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_log_time_user_idx',
            old_name='core_auditl_timesta_328bf1_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_log_action_sev_idx',
            old_name='core_auditl_action_54e21b_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_log_ct_obj_idx',
            old_name='core_auditl_content_fec0c4_idx',
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['content_type', 'object_id', '-timestamp'], name='audit_log_ct_obj_time_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'action', '-timestamp'], name='audit_log_user_act_time_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='audit_log_time_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address', '-timestamp'], name='audit_log_ip_time_idx'),
        ),
    ]
