# Generated by Django 5.1.14 on 2025-11-18 13:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Localização de Estoque',
                'verbose_name_plural': 'Localizações de Estoque',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('type', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste')], max_length=10, verbose_name='Tipo')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantidade')),
                ('document', models.CharField(blank=True, help_text='Número da NF, CF-e, ou outro documento', max_length=100, verbose_name='Documento')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('stock_before', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Estoque Anterior')),
                ('stock_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Estoque Posterior')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='produtos.product', verbose_name='Produto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='movimentaco_product_9c525e_idx'), models.Index(fields=['type', '-created_at'], name='movimentaco_type_9e5e20_idx'), models.Index(fields=['user', '-created_at'], name='movimentaco_user_id_3683a9_idx')],
            },
        ),
    ]
