# Generated by Django 5.2.8 on 2025-11-25 23:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inventorymovement',
            new_name='inv_mov_prod_date_idx',
            old_name='movimentaco_product_9c525e_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorymovement',
            new_name='inv_mov_type_date_idx',
            old_name='movimentaco_type_9e5e20_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorymovement',
            new_name='inv_mov_user_date_idx',
            old_name='movimentaco_user_id_3683a9_idx',
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['product', 'type', '-created_at'], name='inv_mov_prod_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['document'], name='inv_mov_document_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['created_at'], name='inv_mov_created_idx'),
        ),
    ]
