"""
Django settings for siteares project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

try:
    import dj_database_url
    HAS_DJ_DATABASE_URL = True
except ImportError:
    HAS_DJ_DATABASE_URL = False

from decouple import config

def get_bool(env_var, default=False):
    return os.environ.get(env_var, str(default)).lower() in ("true", "1", "t", "yes", "y", "on")

def get_int(env_var, default=0):
    try:
        return int(os.environ.get(env_var, default))
    except (TypeError, ValueError):
        return default
    
SISTEMA_VERSAO = os.environ.get("APP_VERSION", "0.0.1")
AMBIENTE = os.environ.get("AMBIENTE", "tst").lower()

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(PROJECT_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-se&)zrfyqgaz=ogd4r-ad!73@lw!^h#1ldl8cuwl^#@6@p&ox*"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_SETTINGS_DEBUG', 'True').lower() in (
    "true", "1", "t", "yes", "y", "on")

ALLOWED_HOSTS = []

# Uncomment (and adjust as appropriate) to enable django-debug-toolbar
INTERNAL_IPS = [
    "127.0.0.1",
]

# Application definition

INSTALLED_APPS = [
    # App principal do projeto (para wagtail_hooks)
    "siteares.apps.SitearesConfig",
    
    # Apps ARES
    "core",
    "blocks",  # Template tags e componentes reutilizáveis
    "home",  # HomePage pública com Wagtail
    'dashboard',
    'autenticacao',
    'produtos',
    'movimentacoes',
    'relatorios',
    'search',

    "auth_keycloak",
    
    # Autenticação de Dois Fatores (2FA)
    'django_otp',
    'django_otp.plugins.otp_totp',
    'autenticacao_2fa',

    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "modelcluster",
    "taggit",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_browser_reload",
    "webpack_loader",
    "wagtail_color_panel",
    "wagtail.contrib.settings",
    'wagtail.contrib.search_promotions',
    "wagtail.contrib.table_block",
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    "allauth.socialaccount.providers.openid_connect",
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django_filters',
    'drf_yasg',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django_otp.middleware.OTPMiddleware",  # 2FA middleware
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
    "django_browser_reload.middleware.BrowserReloadMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"
ROOT_URLCONF = "siteares.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(PROJECT_DIR, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "wagtail.contrib.settings.context_processors.settings",
                "siteares.context_processors.versao_context",
            ],
        },
    },
]

WSGI_APPLICATION = "siteares.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

if "DATABASE_HOST" in os.environ and "DATABASE_PORT" in os.environ and "DATABASE_NAME" in os.environ and "DATABASE_USERNAME" in os.environ and "DATABASE_PASSWORD" in os.environ:
    DATABASES = {
        "default": {
            "ENGINE": config('DATABASE_ENGINE', default='django.db.backends.postgresql'),
            "HOST": config("DATABASE_HOST"),
            "PORT": config("DATABASE_PORT", default="5432"),
            "NAME": config("DATABASE_NAME"),
            "USER": config("DATABASE_USERNAME"),
            "PASSWORD": config("DATABASE_PASSWORD"),
        },
    }
elif "DATABASE_URL" in os.environ and HAS_DJ_DATABASE_URL:
    DATABASES = {"default": dj_database_url.config(conn_max_age=500)}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
        }
    }


# Cache Configuration
# https://docs.djangoproject.com/en/5.1/topics/cache/

# Use Redis cache if REDIS_URL is configured, otherwise use local memory cache
if "REDIS_URL" in os.environ:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/1"),
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "SOCKET_CONNECT_TIMEOUT": 5,
                "SOCKET_TIMEOUT": 5,
                "CONNECTION_POOL_KWARGS": {
                    "max_connections": 50,
                    "retry_on_timeout": True,
                },
                "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
                "IGNORE_EXCEPTIONS": True,  # Não quebrar se Redis cair
            },
            "KEY_PREFIX": "ares",
            "TIMEOUT": 300,  # 5 minutos padrão
        }
    }
    
    # Session backend usando Redis
    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "default"
else:
    # Fallback para cache em memória local (desenvolvimento)
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
            "TIMEOUT": 300,
            "OPTIONS": {
                "MAX_ENTRIES": 1000
            }
        }
    }

# Cache settings
CACHE_MIDDLEWARE_ALIAS = "default"
CACHE_MIDDLEWARE_SECONDS = 600  # 10 minutos para páginas
CACHE_MIDDLEWARE_KEY_PREFIX = "ares"


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATICFILES_DIRS = [
    os.path.join(PROJECT_DIR, "static"),
    os.path.join(BASE_DIR, 'frontend'),
]

WEBPACK_LOADER = {
    'DEFAULT': {
        # Pasta onde os arquivos compilados serão armazenados
        'BUNDLE_DIR_NAME': 'bundles/',
        'CACHE': not DEBUG,
        'STATS_FILE': os.path.join(BASE_DIR, 'webpack-stats.json'),
        'POLL_INTERVAL': 0.1,
        'IGNORE': [r'.+\.hot-update.js', r'.+\.map'],
    }
}

STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = "/static/"

MEDIA_ROOT = os.getenv('DJANGO_MEDIA_ROOT', os.path.join(PROJECT_DIR, 'media'))
MEDIA_URL = "/media/"

# Override in local settings or replace with your own key. Please don't use our demo key in production!
GOOGLE_MAP_API_KEY = "AIzaSyD31CT9P9KxvNUJOwDq2kcFEIG8ADgaFgw"

# Default storage settings, with the staticfiles storage updated.
# See https://docs.djangoproject.com/en/5.1/ref/settings/#std-setting-STORAGES
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    # ManifestStaticFilesStorage is recommended in production, to prevent
    # outdated JavaScript / CSS assets being served from cache
    # (e.g. after a Wagtail upgrade).
    # See https://docs.djangoproject.com/en/5.1/ref/contrib/staticfiles/#manifeststaticfilesstorage
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
    },
}


# Wagtail settings

WAGTAIL_SITE_NAME = "ARES - Gestão de Estoque"

WAGTAIL_I18N_ENABLED = True

WAGTAIL_CONTENT_LANGUAGES = LANGUAGES = [
    ("en", "English"),
    ("de", "Deutsch"),
    ("ar", "العربيّة"),
    ('pt', 'Portuguese'),
]

WAGTAILIMAGES_AVIF_QUALITY = 60

# Search
# https://docs.wagtail.org/en/stable/topics/search/backends.html

# Use Elasticsearch as the search backend for extra performance and better search results
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
        
    }
}

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
WAGTAILADMIN_BASE_URL = config('WAGTAILADMIN_BASE_URL', default="http://example.com")

# Allowed file extensions for documents in the document library.
# This can be omitted to allow all files, but note that this may present a security risk
# if untrusted users are allowed to upload files -
# see https://docs.wagtail.org/en/stable/advanced_topics/deploying.html#user-uploaded-files
WAGTAILDOCS_EXTENSIONS = ['csv', 'docx', 'key',
                          'odt', 'pdf', 'pptx', 'rtf', 'txt', 'xlsx', 'zip']


# ============================================
# Content Security Policy (CSP)
# ============================================
# Proteção contra XSS, clickjacking e code injection
# Docs: https://django-csp.readthedocs.io/

# CSP habilitado por padrão (modo report-only em dev, enforcement em prod)
CSP_ENABLED = get_bool("CSP_ENABLED", default=True)

if CSP_ENABLED:
    # Adiciona middleware CSP
    if "csp.middleware.CSPMiddleware" not in MIDDLEWARE:
        MIDDLEWARE.append("csp.middleware.CSPMiddleware")
    
    # Modo report-only (dev) ou enforcement (prod)
    CSP_REPORT_ONLY = get_bool("CSP_REPORT_ONLY", default=True)
    
    # ============================================
    # Configurações Padrão Seguras
    # ============================================
    # IMPORTANTE: Valores especiais devem ter aspas: 'self', 'unsafe-inline', 'none'
    
    # Permite customização via variáveis de ambiente ou usa defaults seguros
    if "CSP_DEFAULT_SRC" in os.environ:
        CSP_DEFAULT_SRC = os.environ.get("CSP_DEFAULT_SRC").split(",")
    else:
        CSP_DEFAULT_SRC = ["'self'"]
    
    if "CSP_SCRIPT_SRC" in os.environ:
        CSP_SCRIPT_SRC = os.environ.get("CSP_SCRIPT_SRC").split(",")
    else:
        # ⚠️ 'unsafe-inline' e 'unsafe-eval' necessários para Django admin/Wagtail
        CSP_SCRIPT_SRC = ["'self'", "'unsafe-inline'", "'unsafe-eval'"]
    
    if "CSP_STYLE_SRC" in os.environ:
        CSP_STYLE_SRC = os.environ.get("CSP_STYLE_SRC").split(",")
    else:
        CSP_STYLE_SRC = ["'self'", "'unsafe-inline'"]
    
    if "CSP_IMG_SRC" in os.environ:
        CSP_IMG_SRC = os.environ.get("CSP_IMG_SRC").split(",")
    else:
        # Permite imagens do próprio site, data URIs e HTTPS externo
        CSP_IMG_SRC = ["'self'", "data:", "https:"]
    
    if "CSP_FONT_SRC" in os.environ:
        CSP_FONT_SRC = os.environ.get("CSP_FONT_SRC").split(",")
    else:
        CSP_FONT_SRC = ["'self'", "data:"]
    
    if "CSP_CONNECT_SRC" in os.environ:
        CSP_CONNECT_SRC = os.environ.get("CSP_CONNECT_SRC").split(",")
    else:
        CSP_CONNECT_SRC = ["'self'"]
    
    if "CSP_BASE_URI" in os.environ:
        CSP_BASE_URI = os.environ.get("CSP_BASE_URI").split(",")
    else:
        CSP_BASE_URI = ["'self'"]
    
    if "CSP_OBJECT_SRC" in os.environ:
        CSP_OBJECT_SRC = os.environ.get("CSP_OBJECT_SRC").split(",")
    else:
        # Bloqueia plugins (Flash, Java, etc)
        CSP_OBJECT_SRC = ["'none'"]
    
    # Configurações adicionais de segurança
    CSP_FRAME_ANCESTORS = ["'none'"]  # Previne clickjacking
    CSP_FORM_ACTION = ["'self'"]  # Formulários apenas para próprio site
    
    # Upgrade HTTP para HTTPS (apenas em produção com HTTPS)
    CSP_UPGRADE_INSECURE_REQUESTS = get_bool("CSP_UPGRADE_INSECURE_REQUESTS", default=False)
    
    # Report URI (opcional - endpoint para receber violações CSP)
    if "CSP_REPORT_URI" in os.environ:
        CSP_REPORT_URI = os.environ.get("CSP_REPORT_URI")

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

METABASE_API_KEY = os.environ.get('METABASE_API_KEY', '')  # Busca a chave da API do Metabase via variável de ambiente
METABASE_API_URL = os.environ.get('METABASE_API_URL', 'https://metabase.codata.pb.gov.br/api/card/')  # URL base da API do Metabase
PORTAL_SERVICOS_API_URL = os.environ.get('PORTAL_SERVICOS_API_URL', 'https://api-portal-carta-de-servicos-gedes.rke.codataprd.pb.gov.br/')
PORTAL_SERVICOS_URL = os.environ.get('PORTAL_SERVICOS_URL', 'https://paraibadigital.pb.gov.br/')

# Configurando os backends de autenticação
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Configurações do django allauth
ACCOUNT_ADAPTER = "auth_keycloak.adapters.KeycloakAdapter"

KEYCLOAK_BASE_URL = os.getenv("KEYCLOAK_BASE_URL", "https://homolog.sso.codata.pb.gov.br/auth")
KEYCLOAK_REALM = os.getenv("KEYCLOAK_REALM", "desenvolvimento")

SOCIALACCOUNT_STORE_TOKENS = True
# Configurações do django-allauth para Keycloak
SOCIALACCOUNT_PROVIDERS = {
    "openid_connect": {
        "APPS": [
            {
                "provider_id": os.getenv("SOCIALACCOUNT_PROVIDER_ID", "codata-sso-dev-server"),
                "name": os.getenv("SOCIALACCOUNT_NAME", "CODATA SSO Server"),
                "client_id": os.getenv("KEYCLOAK_CLIENT_ID", "dev-client-secret"),
                "secret": os.getenv("KEYCLOAK_SECRET", ""),
                "settings": {
                    "server_url": os.getenv("KEYCLOAK_SERVER_URL", "https://homolog.sso.codata.pb.gov.br/auth/realms/desenvolvimento/.well-known/openid-configuration"),
                    "logout_url": os.getenv("KEYCLOAK_SERVER_URL_LOGOUT", "https://homolog.sso.codata.pb.gov.br/auth/realms/desenvolvimento/protocol/openid-connect/logout"),
                },
            },
        ]
    }
}

HABILITAR_SSO_LOGIN = get_bool("HABILITAR_SSO_LOGIN", False)
PORTAL_PROVEDOR_CONTEUDO = get_bool("PORTAL_PROVEDOR_CONTEUDO", False)
API_CONTEUDO_AGRUPADO = get_bool("API_CONTEUDO_AGRUPADO", False)

# URL para redirecionar após login bem-sucedido
LOGIN_REDIRECT_URL = "/admin/"

LOGIN_URL = '/admin/login/'
ACCOUNT_LOGIN_URL = '/admin/login/'  # Adicionado para django-allauth
ACCOUNT_LOGIN_METHODS = {'email', 'username'}
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*']
#ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_LOGIN_ON_PASSWORD_RESET = True
ACCOUNT_LOGOUT_REDIRECT_URL = '/admin/login/'
ACCOUNT_PRESERVE_USERNAME_CASING = False
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_USERNAME_BLACKLIST = ["admin", "god"]
ACCOUNT_USERNAME_MIN_LENGTH = 2
ACCOUNT_MAX_EMAIL_ADDRESSES = 1

SITE_ID = 1

# ============================================================================
# DJANGO REST FRAMEWORK CONFIGURATION
# ============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning',
    'DEFAULT_VERSION': 'v1',
    'ALLOWED_VERSIONS': ['v1'],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
    },
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    'DATE_FORMAT': '%Y-%m-%d',
    'TIME_FORMAT': '%H:%M:%S',
}

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Swagger/OpenAPI Configuration
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'USE_SESSION_AUTH': True,
    'JSON_EDITOR': True,
    'SUPPORTED_SUBMIT_METHODS': ['get', 'post', 'put', 'delete', 'patch'],
    'OPERATIONS_SORTER': 'alpha',
    'TAGS_SORTER': 'alpha',
    'DOC_EXPANSION': 'list',
    'DEEP_LINKING': True,
    'SHOW_EXTENSIONS': True,
    'DEFAULT_MODEL_RENDERING': 'example',
}
