# Generated by Django 5.2.8 on 2025-11-25 22:15

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, max_length=300, verbose_name='Introdução')),
                ('body', wagtail.fields.StreamField([('texto_imagem', 4), ('call_to_action', 8), ('destaque', 12), ('heading', 13), ('paragraph', 14), ('image', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'max_length': 100}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texto'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem'}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Esquerda'), ('right', 'Direita')], 'label': 'Posição da Imagem'}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1), ('image', 2), ('image_position', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Texto do Botão', 'max_length': 50}), 6: ('wagtail.blocks.URLBlock', (), {'label': 'Link do Botão'}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Azul Primário'), ('secondary', 'Cinza'), ('success', 'Verde'), ('info', 'Azul Claro'), ('warning', 'Amarelo'), ('danger', 'Vermelho')], 'label': 'Cor de Fundo'}), 8: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1), ('button_text', 5), ('button_link', 6), ('background_color', 7)]], {}), 9: ('wagtail.blocks.TextBlock', (), {'label': 'Descrição', 'max_length': 300}), 10: ('wagtail.blocks.URLBlock', (), {'label': 'Link', 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ex: bi-box, bi-truck, bi-star', 'label': 'Ícone Bootstrap Icons', 'max_length': 50, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 9), ('image', 2), ('link', 10), ('icon', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'label': 'Título'}), 14: ('wagtail.blocks.RichTextBlock', (), {'label': 'Parágrafo'})}, null=True, verbose_name='Conteúdo')),
            ],
            options={
                'verbose_name': 'Página Interna',
                'verbose_name_plural': 'Páginas Internas',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(help_text='Título principal exibido no topo da página', max_length=200, verbose_name='Título Principal')),
                ('hero_subtitle', models.CharField(blank=True, help_text='Subtítulo opcional', max_length=300, verbose_name='Subtítulo')),
                ('banners', wagtail.fields.StreamField([('banner', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'max_length': 100}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Subtítulo', 'max_length': 200, 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Texto do Botão', 'max_length': 50, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'Link do Botão', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('image', 2), ('button_text', 3), ('button_link', 4)]], {})}, null=True, verbose_name='Banners')),
                ('destaques_title', models.CharField(blank=True, default='Nossos Diferenciais', max_length=100, verbose_name='Título da Seção Destaques')),
                ('destaques', wagtail.fields.StreamField([('destaque', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'max_length': 100}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Descrição', 'max_length': 300}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem'}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Link', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ex: bi-box, bi-truck, bi-star', 'label': 'Ícone Bootstrap Icons', 'max_length': 50, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2), ('link', 3), ('icon', 4)]], {})}, null=True, verbose_name='Destaques')),
                ('body', wagtail.fields.StreamField([('texto_imagem', 4), ('call_to_action', 8), ('destaque', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'max_length': 100}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texto'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem'}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Esquerda'), ('right', 'Direita')], 'label': 'Posição da Imagem'}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1), ('image', 2), ('image_position', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Texto do Botão', 'max_length': 50}), 6: ('wagtail.blocks.URLBlock', (), {'label': 'Link do Botão'}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Azul Primário'), ('secondary', 'Cinza'), ('success', 'Verde'), ('info', 'Azul Claro'), ('warning', 'Amarelo'), ('danger', 'Vermelho')], 'label': 'Cor de Fundo'}), 8: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1), ('button_text', 5), ('button_link', 6), ('background_color', 7)]], {}), 9: ('wagtail.blocks.TextBlock', (), {'label': 'Descrição', 'max_length': 300}), 10: ('wagtail.blocks.URLBlock', (), {'label': 'Link', 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ex: bi-box, bi-truck, bi-star', 'label': 'Ícone Bootstrap Icons', 'max_length': 50, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 9), ('image', 2), ('link', 10), ('icon', 11)]], {})}, null=True, verbose_name='Conteúdo')),
                ('noticias_title', models.CharField(blank=True, default='Últimas Notícias', max_length=100, verbose_name='Título da Seção Notícias')),
                ('noticias', wagtail.fields.StreamField([('noticia', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'max_length': 150}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Resumo', 'max_length': 300}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem', 'required': False}), 3: ('wagtail.blocks.DateBlock', (), {'label': 'Data'}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Autor', 'max_length': 100, 'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'label': 'Link completo', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('summary', 1), ('image', 2), ('date', 3), ('author', 4), ('link', 5)]], {})}, null=True, verbose_name='Notícias')),
                ('footer_text', wagtail.fields.RichTextField(blank=True, help_text='Texto adicional para o rodapé', verbose_name='Texto do Rodapé')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem de Fundo')),
            ],
            options={
                'verbose_name': 'Página Inicial',
                'verbose_name_plural': 'Páginas Iniciais',
            },
            bases=('wagtailcore.page',),
        ),
    ]
